### ISSUE TITLE
The SR will not del VDI

### ISSUE THREAD

**Issue by kenneth104** [rposudnevskiy/RBDSR#58]
Hi
My English is not good,Part of the use of google translation

I'm use CEPH RBD Storage_skip(The Xenserver's SR name) in a lot of xenserver

But i'm create and delete VDI in xenserverA , at the same time , in xenserverB will always show the VDI and xencenter not be del the VDI.

create VDI use xapi form template to CEPH RBD Storage_skip , template save as xen local‘s SR
delete VDI use xencenter , remove the VM by deleting the VDI

At last use "`xe vdi-forget uuid=`" can removed VDI in CEPH RBD Storage_skip(The Xenserver's SR name) 

BUT!!!!!!!!!!!!!
Check CEPH use "`ceph -s`"    Will not take up CEPH storage space

picture from xenserverB in xencenter
![del vdi in xencenter](https://user-images.githubusercontent.com/15079279/30247571-3779175a-964a-11e7-9f3e-2e3de563a38f.png)

picture from xenserverB in xencenter
![error vdi](https://user-images.githubusercontent.com/15079279/30247582-4755b0b6-964a-11e7-811e-9e3915c6dd40.png)

**Comment by rposudnevskiy** [comment]
Hi. Are both XenServers in one Xapi pool?

**Comment by kenneth104** [comment]
no , they are alone
must push in one pool?

Suddenly remembered i'm test the NFS shared SR not in one pool have the same problem

**Comment by rposudnevskiy** [comment]
Yes, because servers in one pool use one Xapi database for all servers. If they are not in one pool then the each server uses its own database so if you delete Vdi from the first server the second server will not know about it. The second server will keep information about this Vdi in its own database in spite of this Vdi has already been deleted from storage. So if you try delete this Vdi again on the second server you will receive an error because Vdi has already been deleted from the storage. And the only thing you can do in such case is forget Vdi on the second server, what you already did using xe vdi-forget. 
Vdi-forget just remove Vdi from database not from storage.

**Comment by kenneth104** [comment]
oh~
Thanks a lot
Relevant problems plagued me for a long time

**Comment by kenneth104** [comment]
I think use shared SR，the database will in shared
but,it's wrong

**Comment by rposudnevskiy** [comment]
I'm happy to help  
The servers should be in the pool to be synchronized. It gives you not only single SR for all server but single network configuration, HA, the live migration between servers with shared storage will work much faster as it just remap Vdi to other server. If the servers are not in a pool the Xapi uses cross-pool migration which implies the coping of Vdi between servers and it can take a long time.
